# Generated by Django 3.1.4 on 2021-01-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claimapp', '0002_application_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('claimTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.claimtype')),
            ],
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('serviceType', models.CharField(default='GET', max_length=30)),
                ('url', models.URLField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='RoleLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('periodUom', models.CharField(max_length=30)),
                ('period', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('maxYears', models.IntegerField(blank=True, null=True)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='EntityElement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('elementId', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('calculationMethod', models.CharField(default='service', max_length=30)),
                ('fixedAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('entityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.entity')),
                ('serviceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claimapp.elementtype')),
            ],
        ),
        migrations.CreateModel(
            name='EntityApplication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.application')),
                ('entityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionElementType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('decisionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.decision')),
                ('elementTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.elementtype')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.role'),
        ),
        migrations.CreateModel(
            name='ClaimTypeElement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('claimTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.claimtype')),
                ('elementTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimapp.elementtype')),
            ],
        ),
    ]
