# Generated by Django 3.1.4 on 2021-01-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claimapp', '0003_auto_20210105_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityElement',
            new_name='EntityElementType',
        ),
    ]
