# Generated by Django 3.1.3 on 2020-12-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
