# Generated by Django 3.1.3 on 2020-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
